dataset_name: 'humaneval'
model_path: "../llms/GSAI-ML/LLaDA-8B-Instruct"
data_root: "./data"

dataset_config:
  data_loader: 'huggingface'
  loader_fn: null
  load_dataset_args: { path: "humaneval" }
  split: "test"
  doc_to_text_fn: "humaneval_doc_to_text"
  extract_answer_fn: "humaneval_extract_answer"   
  output_formatter: 'humaneval'
  problem_file: "./data/humaneval/HumanEval.jsonl"
  problem_file_et: './data/humaneval/HumanEval_ET.jsonl'

generation_args: { gen_length: 256, block_length: 256, temperature: 0.0 }
method: 'saber' 
method_args:
  wino: { threshold: 0.7, threshold_back: 0.9 }