dataset_name: 'livecodebench'
model_path: "../llms/GSAI-ML/LLaDA-8B-Instruct"
data_root: "./data"

dataset_config:
  data_loader: 'custom_loader'
  loader_fn: 'mbpp_read_data'
  load_dataset_args: { path: "livecodebench/test.jsonl" }
  split: null
  doc_to_text_fn: "lcb_doc_to_text"
  extract_answer_fn: "lcb_extract_answer"
  output_formatter: 'livecodebench'
  problem_file: "livecodebench/test.jsonl"

generation_args: { gen_length: 256, block_length: 256, temperature: 0.0 }
method: 'saber'